contracts/DCAHubCompanion/DCAHubCompanionMulticallHandler.sol, contracts/DCAHubCompanion/DCAHubCompanionParameters.sol, contracts/DCAHubCompanion/DCAHubCompanionSwapHandler.sol, contracts/DCAHubCompanion/DCAHubCompanionWTokenPositionHandler.sol, contracts/interfaces/IDCAHubCompanion.sol, contracts/mocks/DCAHubCompanion/DCAHubCompanionMulticallHandler.sol, contracts/mocks/DCAHubCompanion/DCAHubCompanionWTokenPositionHandler.sol, test/unit/DCAHubCompanion/dca-hub-companion-multi-call-handler.spec.ts, test/unit/DCAHubCompanion/dca-hub-companion-parameters.spec.ts, test/unit/DCAHubCompanion/dca-hub-companion-swap-handler.spec.ts, test/unit/DCAHubCompanion/dca-hub-companion-wtoken-position-handler.spec.ts
We are now adding support for tokens like USDT, that don't allow us to approve a new amount of tokens if the allowance is already more than zero.
=> refactor: support tokens with approval issues

contracts/DCAHubCompanion/DCAHubCompanion.sol, contracts/DCAHubCompanion/DCAHubCompanionMulticallHandler.sol, contracts/DCAHubCompanion/DCAHubCompanionParameters.sol, contracts/DCAHubCompanion/DCAHubCompanionSwapHandler.sol, contracts/DCAHubCompanion/DCAHubCompanionWTokenPositionHandler.sol, contracts/interfaces/IDCAHubCompanion.sol, contracts/mocks/DCAHubCompanion/DCAHubCompanionMulticallHandler.sol, contracts/mocks/DCAHubCompanion/DCAHubCompanionWTokenPositionHandler.sol, deploy/000_register_hub.ts, package.json, test/integration/DCAHubCompanion/multi-call.spec.ts, test/integration/fork-block-numbers.ts, test/unit/DCAHubCompanion/dca-hub-companion-multi-call-handler.spec.ts, test/unit/DCAHubCompanion/dca-hub-companion-parameters.spec.ts, test/unit/DCAHubCompanion/dca-hub-companion-swap-handler.spec.ts, test/unit/DCAHubCompanion/dca-hub-companion-wtoken-position-handler.spec.ts, yarn.lock
We are now making the first step towards adding the multicall handler. The idea is to support multiple calls in one tx, like:
- Give the companion permissions and withdraw as eth
- Execute withdraws from swapped and unswapped balance in one tx, without terminating
In order to support these use cases, we need to add calls these "proxy calls" in the companion, so we can then use them in the multicall
=> feat: add multicall handler

contracts/DCAKeep3rJob/DCAKeep3rJob.sol, contracts/mocks/DCAKeep3rJob/DCAKeep3rJob.sol, deploy/003_keep3r_job.ts, test/integration/DCAKeep3rJob/keep3r-job.spec.ts, test/unit/DCAKeep3rJob/dca-keep3r-job.spec.ts
In order to be able to deploy the keep3r job and start acquiring keep3r credits through `V2` we need to deploy the keep3r job alone. This PR solves that.
=> refactor: keep3r job no longer needs swapper to be set in deployment

contracts/DCAHubCompanion/DCAHubCompanionMulticallHandler.sol, contracts/DCAHubCompanion/DCAHubCompanionWTokenPositionHandler.sol, contracts/DCAHubCompanion/utils/Multicall.sol, contracts/interfaces/IDCAHubCompanion.sol, test/integration/DCAHubCompanion/multi-call.spec.ts, test/integration/DCAHubCompanion/wtoken-integration.spec.ts, test/integration/DCAKeep3rJob/keep3r-job.spec.ts, test/unit/DCAHubCompanion/dca-hub-companion-wtoken-position-handler.spec.ts
Before this change, we couldn't execute payable functions in Multicall. This was a problem, since we couldn't execute `increasePositionUsingProtocolToken`
Now, our custom Multicall supports both payable and non-payable functions
=> feat: supporting payable multicalls

test/integration/DCAHubCompanion/multi-pair-swap-with-dex.spec.ts, test/integration/DCAHubCompanion/single-pair-swap-with-dex.spec.ts
We are now making two changes that should make swap tests more reliable:
- We are using the Uniswap oracle as the source of truth. Before, when we used Chainlink, it could happen that the price would be different from the current state of the market
- We are passing `takerAddress` to 0x, which makes it more reliable
=> test: use uniswap oracle for swap tests

contracts/DCAFeeManager/DCAFeeManager.sol, contracts/interfaces/IDCAFeeManager.sol, test/unit/DCAFeeManager/dca-fee-manager.spec.ts
We are basically undoing #77. I realized that it would be better if the action to take fees and send fill positions was permissioned, so we can just take the distribution as a parameter, instead of having it stored
My bad 😅
=> refactor: remove token distribution

contracts/DCAFeeManager/DCAFeeManager.sol, contracts/interfaces/IDCAFeeManager.sol, test/unit/DCAFeeManager/dca-fee-manager.spec.ts
We are now adding a new method called `terminatePositions` . This is meant to be used only if for some reason swaps are
no longer executed
=> feat: add terminate positions

contracts/DCAFeeManager/DCAFeeManager.sol, contracts/interfaces/IDCAFeeManager.sol, test/unit/DCAFeeManager/dca-fee-manager.spec.ts
We are now adding a way to reset the allowance for a specific token. Anyone will be able to pay the gas cost of doing so
=> feat: add reset allowance

contracts/DCAFeeManager/DCAFeeManager.sol, contracts/interfaces/IDCAFeeManager.sol, test/integration/DCAFeeManager/dca-fee-manager.spec.ts, test/unit/DCAFeeManager/dca-fee-manager.spec.ts
Before this change, when we called `withdrawProtocolToken`, we would always withdraw WETH (or the wToken) from the platform balance. Now, we can specify if we want to do so or not
=> feat: enable specifying if withdraw from platfrom

contracts/DCAFeeManager/DCAFeeManager.sol, contracts/interfaces/IDCAFeeManager.sol, contracts/mocks/DCAFeeManager/DCAFeeManager.sol, test/integration/DCAFeeManager/dca-fee-manager.spec.ts, test/unit/DCAFeeManager/dca-fee-manager.spec.ts
We are now making a small change where we store all created positions in an array. This will allow us to return all position when `availableBalances` is called, and therefore there will be no need for an off-chain way to find the positions.
This should make the entire UX much easier to use.
Also, since we can return everything in `availableBalances`, we removed `positionBalances`
=> feat: store position ids

contracts/DCAFeeManager/DCAFeeManager.sol, contracts/interfaces/IDCAFeeManager.sol, contracts/mocks/DCAFeeManager/DCAFeeManager.sol, deploy/005_fee_manager.ts, test/integration/DCAFeeManager/dca-fee-manager.spec.ts, test/integration/DCAHubSwapper/swap-for-caller.spec.ts, test/unit/DCAFeeManager/dca-fee-manager.spec.ts, test/utils/swap-utils.ts
We are now adding access management. The contract owner/governor will be able to give other users the ability to set the target tokens distribution, and also make withdraws (in future PRs)
=> feat: add access management

contracts/DCAFeeManager/DCAFeeManager.sol, contracts/interfaces/IDCAFeeManager.sol, contracts/mocks/DCAFeeManager/DCAFeeManager.sol, deploy/005_fee_manager.ts, test/unit/DCAFeeManager/dca-fee-manager.spec.ts
After all the recent PRs, we can now stop taking the hub as a contract parameter
=> refactor: stop taking hub as contract parameter

contracts/DCAFeeManager/DCAFeeManager.sol, contracts/interfaces/IDCAFeeManager.sol, contracts/mocks/DCAFeeManager/DCAFeeManager.sol, deploy/005_fee_manager.ts, test/integration/DCAFeeManager/dca-fee-manager.spec.ts, test/unit/DCAFeeManager/dca-fee-manager.spec.ts
We are now taking the Hub as a parameter when calling `availableBalances`
=> refactor: take hub address available balances

contracts/DCAFeeManager/DCAFeeManager.sol, contracts/interfaces/IDCAFeeManager.sol, contracts/mocks/DCAFeeManager/DCAFeeManager.sol, deploy/005_fee_manager.ts, test/integration/DCAFeeManager/dca-fee-manager.spec.ts, test/unit/DCAFeeManager/dca-fee-manager.spec.ts
We are now taking the Hub as a parameter when calling `terminatePositions`
=> refactor: take hub address terminate positions

contracts/DCAFeeManager/DCAFeeManager.sol, contracts/interfaces/IDCAFeeManager.sol, contracts/mocks/DCAFeeManager/DCAFeeManager.sol, deploy/005_fee_manager.ts, test/integration/DCAFeeManager/dca-fee-manager.spec.ts, test/unit/DCAFeeManager/dca-fee-manager.spec.ts
We are now taking the Hub as a parameter when calling `withdrawFromPositions`
=> refactor: take hub address withdraw from positions

contracts/DCAFeeManager/DCAFeeManager.sol, contracts/interfaces/IDCAFeeManager.sol, contracts/mocks/DCAFeeManager/DCAFeeManager.sol, deploy/005_fee_manager.ts, test/integration/DCAFeeManager/dca-fee-manager.spec.ts, test/unit/DCAFeeManager/dca-fee-manager.spec.ts
We are now deleting `resetAllowance` and handling everything internally. It didn't make much sense to have it in another function, since `fillPositions` would revert until `resetAllowance` was called
=> refactor: handle allowance reset internally

contracts/DCAFeeManager/DCAFeeManager.sol, contracts/interfaces/IDCAFeeManager.sol, contracts/mocks/DCAFeeManager/DCAFeeManager.sol, deploy/005_fee_manager.ts, test/integration/DCAFeeManager/dca-fee-manager.spec.ts, test/unit/DCAFeeManager/dca-fee-manager.spec.ts
The Fee Manager currently takes a DCAHub address on the constructor. Since it's immutable, it cannot be changed. We could make it mutable, but that would make all actions more expensive
The idea is to add the hub as a parameter to all actions, so that the same Fee Manager can work for multiple hubs at the same time
=> refactor: take hub address withdraw platform balance

contracts/DCAFeeManager/DCAFeeManager.sol, contracts/interfaces/IDCAFeeManager.sol, contracts/mocks/DCAFeeManager/DCAFeeManager.sol, deploy/005_fee_manager.ts, test/integration/DCAFeeManager/dca-fee-manager.spec.ts, test/unit/DCAFeeManager/dca-fee-manager.spec.ts, test/utils/behaviours.ts
We are now simplifying the Fee Manager. We had a governor + allowed. This was basically AccessControl with two different roles. For consistency, we are moving towards AccessControl + Super Admin + Admins, like in our other repos
Look at all that deleted code
=> refactor: change governable for access control

contracts/DCAHubCompanion/DCAHubCompanionMulticallHandler.sol, contracts/DCAHubCompanion/DCAHubCompanionParameters.sol, contracts/interfaces/IDCAHubCompanion.sol, test/integration/DCAHubCompanion/multi-call.spec.ts, test/unit/DCAHubCompanion/dca-hub-companion-multi-call-handler.spec.ts
We continue with small changes. Right now, we are no longer taking tokens from the caller when executing `depositProxy` or `increasePositionProxy`
=> refactor: avoid taking tokens from caller

contracts/DCAHubCompanion/DCAHubCompanion.sol, contracts/DCAHubCompanion/DCAHubCompanionHubProxyHandler.sol, contracts/interfaces/IDCAHubCompanion.sol, contracts/mocks/DCAHubCompanion/DCAHubCompanionHubProxyHandler.sol, test/unit/DCAHubCompanion/dca-hub-companion-multi-call-handler.spec.ts
We are now renaming the `DCAHubCompanionMulticallHandler` to `DCAHubCompanionHubProxyHandler`. Also, we moved the `Multicall` contract from the `DCAHubCompanionMulticallHandler` to the `DCAHubCompanion`
=> refactor: rename multicall handler

contracts/DCAHubCompanion/DCAHubCompanionHubProxyHandler.sol, contracts/interfaces/IDCAHubCompanion.sol, contracts/mocks/DCAHubCompanion/DCAHubCompanionHubProxyHandler.sol, test/unit/DCAHubCompanion/dca-hub-companion-hub-proxy-handler.spec.ts
One of the new use cases that we want to enable is:
1. Take token from user
2. Convert token to another token (maybe the yield-bearing version of the original token)
3. Deposit the converted token to the Hub
Since slippage can happen in the conversion, the idea is to have a function that takes the Companion's entire balance
=> feat: deposit with all balance

contracts/DCAHubSwapper/DCAHubSwapper.sol, contracts/DCAHubSwapper/DCAHubSwapperParameters.sol, contracts/DCAHubSwapper/DCAHubSwapperSwapHandler.sol, contracts/interfaces/IDCAHubSwapper.sol, contracts/mocks/DCAHubSwapper/DCAHubSwapperSwapHandler.sol, contracts/mocks/ISwapper.sol, deploy/002_swapper.ts, test/integration/V2Migration/position-migrator.spec.ts, test/unit/DCAHubSwapper/dca-hub-swapper-swap-handler.spec.ts
We are now adding a new kind of swap to our DCASwapper (it's not yet callable, we are now simply handling the Hub's callback).
There are three main changes between this swap with dex and the previous one:
1. Our current swapWithDex allows the DCASwapper to take one dex, and multiple swaps (with that dex). Now, we are taking multiple swappers and multiple executions. This will allow us to choose better paths for our swaps, and handle more complex situations (like `USDC => yUSDC => WETH => yWETH`)
2. The current `swapWithDex` would handle approvals per swap. This meant that we would approve only what was needed, and we also needed to tackle special tokens, like USDT. Now, we are giving max approvals, which is **far** cheaper
3. Previously, we had a flag that would specify if the swap was a …
=> feat: add new handle with dexes

contracts/DCAHubSwapper/DCAHubSwapperSwapHandler.sol, contracts/interfaces/IDCAHubSwapper.sol, contracts/mocks/DCAHubSwapper/DCAHubSwapperSwapHandler.sol, test/unit/DCAHubSwapper/dca-hub-swapper-swap-handler.spec.ts
We are now adding `swapWithDexes` and `swapWithDexesByMeanKeepers` (open to change the name on the second one, but I'm not sure what to name it)
These functions basically initiate the DCA swap that will handled by the new code in #109
**Note**: the integration tests fail with `InvalidInputError: Transaction gas limit is 30006104 and exceeds block gas limit of 30000000` because the swapper cannot be deployed. This is fixed in the next PR, when we delete a lot of the contract's code
=> feat: add swap with dexes

contracts/DCAHubCompanion/DCAHubCompanion.sol, contracts/DCAHubCompanion/DCAHubCompanionTakeSendAndSwapHandler.sol, contracts/mocks/DCAHubCompanion/DCAHubCompanionTakeSendAndSwapHandler.sol, deploy/001_companion.ts, package.json, test/unit/DCAHubCompanion/dca-hub-companion-take-send-and-swap-handler.spec.ts, yarn.lock
We doing a few things in this PR:
1. We are using the internal function for `sendToRecipient`
2. We are adding the following extensions to the companion:
- `RunSwap`: so we can execute swaps
- `RevokableWithGovernor`: to revoke potential access
- `GetBalances `: to be able to easily read the contract's balance
3. Also, we fixed the Companion's deployment that was working on the tests for some reason 😆
=> feat: add swap extensions to companion

contracts/DCAHubSwapper/DCAHubSwapperSwapHandler.sol, test/integration/DCAFeeManager/dca-fee-manager.spec.ts, test/integration/DCAHubCompanion/multi-call.spec.ts, test/integration/DCAHubSwapper/multi-pair-swap-with-dex.spec.ts, test/integration/DCAHubSwapper/single-pair-swap-with-dex.spec.ts, test/integration/DCAHubSwapper/swap-for-caller.spec.ts, test/integration/V2Migration/position-migrator.spec.ts, test/unit/DCAHubSwapper/dca-hub-swapper-swap-handler.spec.ts
We are now making it so that swaps in the DCASwapper can only be executed by addressed with the `SWAP_EXECUTION_ROLE` role
=> feat: make dca swapper permissioned

contracts/DCAHubSwapper/DCAHubSwapper.sol, contracts/mocks/DCAHubSwapper/DCAHubSwapper.sol, deploy/002_swapper.ts, test/integration/V2Migration/position-migrator.spec.ts, test/unit/DCAHubSwapper/dca-hub-swapper.spec.ts
We are now making a small change. We are bringing back the "super admin role" so now everything is consistent with the rest of the permissioned contracts, and we are setting it as its own admin
=> refactor: change swappers permissions

contracts/DCAHubSwapper/DCAHubSwapper.sol, contracts/interfaces/IDCAHubSwapper.sol, contracts/mocks/DCAHubSwapper/DCAHubSwapper.sol, test/unit/DCAHubSwapper/dca-hub-swapper.spec.ts
We are now adding `revokeAllowances` and `sendDust` to the DCAHubSwapper
=> feat: add revoke and send dust

contracts/DCAHubSwapper/DCAHubSwapper.sol, contracts/interfaces/IDCAHubSwapper.sol, contracts/interfaces/ILegacyDCAHub.sol, deploy/002_swapper.ts, package.json, test/unit/DCAHubSwapper/dca-hub-swapper.spec.ts, yarn.lock
We are now adding a way to execute `swapForCaller` for legacy hubs
=> feat: add legacy swap for caller

contracts/DCAHubCompanion/DCAHubCompanionLibrariesHandler.sol, contracts/interfaces/IDCAHubCompanion.sol, contracts/libraries/SecondsUntilNextSwap.sol, contracts/mocks/libraries/SecondsUntilNextSwap.sol, test/unit/libraries/seconds-until-next-swap.spec.ts
We are now taking into consideration the new privileged role when calculating `secondsUntilNextSwap`
=> refactor: consider privilege on seconds until next swap

contracts/DCAHubSwapper/DCAHubSwapper.sol, contracts/interfaces/IDCAHubSwapper.sol, package.json, test/integration/DCAHubSwapper/optimized-multi-pair-swap-with-dex.spec.ts, test/unit/DCAHubSwapper/dca-hub-swapper.spec.ts
We are now adding `optimizedSwap`. This function will the take the data for the callback already encoded, so we can avoid doing the encoding in the smart contract. This has proven to be cheaper, with 22k savings
=> perf: add optimized swap

test/integration/DCAHubCompanion/multi-call.spec.ts
We now have four multi call tests that do not involve swaps:
- Withdraw swapped and create a new position with it (already existed, just refactored)
- Withdraw swapped and unswapped balance in one tx, without terminating (already existed, just refactored)
- Take from caller and create multiple positions
- Withdraw swapped and then distribute to many recipients
=> test: add non swap multi call

contracts/utils/BaseCompanion.sol, test/unit/utils/base-companion.spec.ts
We are now adding a way to execute a permit on a ERC20 token, so that we can permit + deposit with a multicall
=> feat: token permit

contracts/DCAStrategies/DCAStrategies/DCAStrategiesPositionsHandler.sol, contracts/interfaces/IDCAStrategies.sol, test/unit/DCAStrategies/dca-strategies-positions-handler.spec.ts
- add code to save user position
- tests
I had to make this [mapping](https://github.com/Mean-Finance/dca-v2-periphery/blob/feat/user-position/contracts/DCAStrategies/DCAStrategies/DCAStrategiesPositionsHandler.sol#L10) internal and expose a function to returns its value because of a strange error when overriding a mapping that returns a struct.
Also, I moved the loop logic to an [internal function](https://github.com/Mean-Finance/dca-v2-periphery/blob/feat/user-position/contracts/DCAStrategies/DCAStrategies/DCAStrategiesPositionsHandler.sol#L120) because of `stack to deep error`.
=> feat: user-position

contracts/DCAHubSwapper/DCAHubSwapper.sol, contracts/interfaces/IDCAHubSwapper.sol, contracts/mocks/LegacyDCASwapper.sol, test/integration/DCAHubCompanion/position-migrator.spec.ts, test/unit/DCAHubSwapper/dca-hub-swapper.spec.ts
We are now deleting `legacySwapForCaller`, `legacySwapWithDexes` and `legacySwapWithDexesForMean`. We decided that if we want to interact with the legacy Hubs, we will use the old DCA Swapper
=> refactor: delete legacy functions

contracts/DCAHubSwapper/DCAHubSwapper.sol, contracts/interfaces/IDCAHubSwapper.sol, contracts/mocks/DCAHubSwapper/DCAHubSwapper.sol, test/integration/DCAHubSwapper/multi-pair-swap-with-dex.spec.ts, test/integration/DCAHubSwapper/optimized-multi-pair-swap-with-dex.spec.ts, test/integration/DCAHubSwapper/single-pair-swap-with-dex.spec.ts, test/unit/DCAHubSwapper/dca-hub-swapper.spec.ts
We realized that in complex swaps (like yield(WETH) => WETH => USDC), we might have intermediate tokens. But we don't have a way to check these tokens for unspent balance. So we are adding this
=> feat: add intermediate tokens

contracts/DCAHubSwapper/ThirdPartyDCAHubSwapper.sol, test/unit/DCAHubSwapper/third-party-dca-hub-swapper.spec.ts
We are now introducing a new DCA Swapper. This Swapper is meant to only support third-party swaps, not swaps for caller
This means that no-one should be approving tokens for this contract. Since that's the case, and the contract is not meant to hold any tokens, we can call any arbitrary data
Therefore, we can avoid using the TransformerRegistry and interact with 4626s directly 🚀 
Also, in the existing swapper, the workflow is DCASwapper => DCAHub => DCASwapper
Now, we only do DCAHub => DCASwapper, which should be much cheaper in terms of gas 🤑
=> feat: add third party dca swapper

deploy/005_keep3r_job.ts, test/integration/DCAKeep3rJob/keep3r-job.spec.ts
We are now using the new swapper for the Keep3r job
In doing so, we reduced the work job by 19k! And we were only swapping one pair 💪
=> refactor: use new swapper for keep3r job

contracts/DCAHubSwapper/CallerOnlyDCAHubSwapper.sol, contracts/mocks/DCAHubSwapper/CallerOnlyDCAHubSwapper.sol, deploy/002_caller_only_swapper.ts, test/integration/DCAFeeManager/dca-fee-manager.spec.ts, test/integration/DCAHubCompanion/multi-call.spec.ts, test/integration/DCAHubSwapper/swap-for-caller.spec.ts, test/integration/utils.ts, test/unit/DCAHubSwapper/caller-only-dca-hub-swapper.spec.ts
We are renaming the old swapper so that it's clear that it will only support "swap for caller" only
=> refactor: rename old swapper

contracts/DCAHubSwapper/ThirdPartyDCAHubSwapper.sol, test/integration/DCAHubSwapper/multi-pair-swap-with-dex.spec.ts, test/integration/DCAHubSwapper/swap-with-dex-native.spec.ts, test/integration/DCAKeep3rJob/keep3r-job.spec.ts, test/unit/DCAHubSwapper/third-party-dca-hub-swapper.spec.ts
There are some cases where the oracles differ from what the markets can offer, so a swap can't be executed. But it could happen that even if the amounts being swap are really big, the difference between oracle and market is only a few dollars. In that case, it would be nice if someone could just pay for the difference.
The idea here is that instead of calling the hub directly, someone could call the swapper with some native token, so that when the swapper gets called, they can use that native token balance as part of the swap, and cover the difference
The normal workflow is:
`Caller => Hub => Swapper => Hub`
Here, it would be:
`Caller => Swapper => Hub => Swapper => Hub`
It would be more expensive, but again, it would be optional
_Note: this change required us to include a new property …
=> feat: add execute swap

contracts/DCAHubCompanion/DCAHubCompanionHubProxyHandler.sol, contracts/interfaces/IDCAHubCompanion.sol, test/unit/DCAHubCompanion/dca-hub-companion-hub-proxy-handler.spec.ts
We are now simply adding a new call to the companion. This call will allow us to execute multi-permissions. These are signature permissions that modify multiple positions, with only one signature
This call doesn't need any checks, since it's just about sending the signature permit to the permission manager
=> feat: add multi permission permit to companion

contracts/DCAHubCompanion/DCAHubCompanion.sol, contracts/libraries/Permit2Transfers.sol, contracts/mocks/utils/BaseCompanion.sol, contracts/utils/BaseCompanion.sol, deploy/001_companion.ts, package.json, test/integration/DCAHubCompanion/multi-call.spec.ts, test/unit/utils/base-companion.spec.ts, test/utils/behaviours.ts, yarn.lock
We are now making a change to the Companion so that we don't have to use the swapper registry. Before this change, we would call swappers directly from the Companion, which would be an arbitrary address. Since they Companion also handles approvals, we would need a whitelist (the registry) to make sure funds couldn't be transferred. Despite all this, when we used the swapper, we would actually use the SwapProxy because it supported multi-step swaps. 
So the idea here it that the Companion will now have a pre-defined swapper (and allowance target), instead of taking an arbitrary address. This will allow us to get rid of the whitelist.
The regular workflow will looks something like:
1. Companion use Permit2 to transfer tokens from the caller to the Permit2Adapter contract
2. Companion calls …
=> refactor: remove swap registry from companion

.github/workflows/tests.yml, contracts/DCAFeeManager/DCAFeeManager.sol, contracts/DCAHubCompanion/DCAHubCompanion.sol, contracts/interfaces/IDCAFeeManager.sol, contracts/interfaces/external/IPermit2.sol, contracts/libraries/Permit2Transfers.sol, contracts/mocks/DCAFeeManager/DCAFeeManager.sol, contracts/mocks/utils/BaseCompanion.sol, contracts/utils/BaseCompanion.sol, deploy/001_companion.ts, deploy/004_fee_manager.ts, package.json, test/integration/DCAFeeManager/dca-fee-manager.spec.ts, test/integration/DCAHubCompanion/multi-call.spec.ts, test/unit/DCAFeeManager/dca-fee-manager.spec.ts, test/unit/utils/base-companion.spec.ts, test/utils/behaviours.ts, yarn.lock
We are now adding a way to take tokens from the caller by using Permit2, instead of the regular `approve` + `transferFrom`
=> feat: add take with permit to base companion

contracts/DCAHubSwapper/ThirdPartyDCAHubSwapper.sol, deploy/003_third_party_swapper.ts, test/integration/DCAHubSwapper/multi-pair-swap-with-dex.spec.ts, test/integration/DCAHubSwapper/swap-with-dex-native.spec.ts, test/unit/DCAHubSwapper/third-party-dca-hub-swapper.spec.ts
We are now making two changes:
1. We are removing the `sendToProvideLeftoverToHub` flag. We are the only ones using this contract, and it was always set to true, so it didn't make much sense to have it anymore
2. We are adding an `isTest` flag. If set to true, we will calculate all balances on the contract and report them via revert. This will allow us to simulate quotes 🔥
=> refactor: add test mode to 3rd party swapper
