Mean-Finance/dca-v2-periphery

contracts/DCAHubCompanion/DCAHubCompanionMulticallHandler.sol
contracts/DCAHubCompanion/DCAHubCompanionParameters.sol
contracts/DCAHubCompanion/DCAHubCompanionWTokenPositionHandler.sol

We are now reducing the contract size so that it can be deployed

chore: reduce contract size

---

contracts/DCAHubCompanion/DCAHubCompanionMulticallHandler.sol
contracts/DCAHubCompanion/DCAHubCompanionParameters.sol
contracts/DCAHubCompanion/DCAHubCompanionSwapHandler.sol
contracts/DCAHubCompanion/DCAHubCompanionWTokenPositionHandler.sol
contracts/interfaces/IDCAHubCompanion.sol
contracts/mocks/DCAHubCompanion/DCAHubCompanionMulticallHandler.sol
contracts/mocks/DCAHubCompanion/DCAHubCompanionWTokenPositionHandler.sol
test/integration/DCAHubCompanion/multi-call.spec.ts
test/unit/DCAHubCompanion/dca-hub-companion-multi-call-handler.spec.ts
test/unit/DCAHubCompanion/dca-hub-companion-parameters.spec.ts
test/unit/DCAHubCompanion/dca-hub-companion-swap-handler.spec.ts
test/unit/DCAHubCompanion/dca-hub-companion-wtoken-position-handler.spec.ts

Initially, I though there was no need for a deposit proxy. But then I realized there was a good use case for it.
What if someone wanted to withdraw funds from their position and create a new position with that balance? So I created the deposit proxy, so it can all be done in one tx

feat: implement deposit proxy

---

contracts/DCAHubCompanion/DCAHubCompanion.sol
contracts/DCAHubCompanion/DCAHubCompanionMulticallHandler.sol
contracts/DCAHubCompanion/DCAHubCompanionParameters.sol
contracts/DCAHubCompanion/DCAHubCompanionSwapHandler.sol
contracts/DCAHubCompanion/DCAHubCompanionWTokenPositionHandler.sol
contracts/interfaces/IDCAHubCompanion.sol
contracts/mocks/DCAHubCompanion/DCAHubCompanionMulticallHandler.sol
contracts/mocks/DCAHubCompanion/DCAHubCompanionWTokenPositionHandler.sol
deploy/000_register_hub.ts
package.json
test/integration/DCAHubCompanion/multi-call.spec.ts
test/integration/fork-block-numbers.ts
test/unit/DCAHubCompanion/dca-hub-companion-multi-call-handler.spec.ts
test/unit/DCAHubCompanion/dca-hub-companion-parameters.spec.ts
test/unit/DCAHubCompanion/dca-hub-companion-swap-handler.spec.ts
test/unit/DCAHubCompanion/dca-hub-companion-wtoken-position-handler.spec.ts
yarn.lock

We now implemented `Multicall` and added some tests that use it

feat: implement multicall

---

.github/workflows/gas-report.yml
.github/workflows/tests.yml
deploy/000_register_hub.ts
deploy/001_companion.ts
test/integration/DCAHubCompanion/multi-call.spec.ts
test/integration/DCAHubCompanion/multi-pair-swap-with-dex.spec.ts
test/integration/DCAHubCompanion/single-pair-swap-with-dex.spec.ts
test/integration/DCAHubCompanion/swap-for-caller.spec.ts
test/integration/DCAHubCompanion/wtoken-integration.spec.ts
test/integration/fork-block-numbers.ts
test/utils/evm.ts
test/utils/zrx.ts
utils/network.ts

We are now making some changes, so that all tests are run on optimism or optimism-kovan

test: run all tests on optimism

---

contracts/V2Migration/BetaMigrator.sol
deploy/002_beta_migrator.ts
test/integration/DCAHubCompanion/multi-call.spec.ts
test/integration/DCAHubCompanion/multi-pair-swap-with-dex.spec.ts
test/integration/V2Migration/beta-migrator.spec.ts
test/integration/fork-block-numbers.ts

We are now adding a new contract, to migrate users from the beta into the new full version of the Hub

feat: add beta migrator

---

deploy/000_register_hub.ts
deploy/003_keep3r_job.ts
test/integration/DCAKeep3rJob/keep3r-job.spec.ts
test/integration/abis/Keep3r.json
test/integration/abis/UniV3PairManager.json

We are now adding the missing integration tests for keep3r v2

test: add keep3r integration tests

---

contracts/DCAHubCompanion/DCAHubCompanionMulticallHandler.sol
contracts/DCAHubCompanion/DCAHubCompanionWTokenPositionHandler.sol
contracts/interfaces/IDCAHubCompanion.sol
package.json
test/integration/DCAHubCompanion/multi-call.spec.ts
test/integration/DCAHubCompanion/multi-pair-swap-with-dex.spec.ts
test/integration/DCAHubCompanion/single-pair-swap-with-dex.spec.ts
test/integration/DCAHubCompanion/swap-for-caller.spec.ts
test/integration/DCAHubCompanion/wtoken-integration.spec.ts
test/integration/DCAKeep3rJob/keep3r-job.spec.ts
test/integration/V2Migration/beta-migrator.spec.ts
test/unit/DCAHubCompanion/dca-hub-companion-multi-call-handler.spec.ts
test/unit/DCAHubCompanion/dca-hub-companion-swap-handler.spec.ts
test/unit/DCAHubCompanion/dca-hub-companion-wtoken-position-handler.spec.ts
test/utils/erc20.ts
yarn.lock

We are making two changes here:
1. We are adding `misc` to all functions that end up executing `deposit`
2. We are no longer supporting special deposits on the companion where the protocol token is `to`

feat: add misc

---

contracts/DCAFeeManager/DCAFeeManager.sol
contracts/interfaces/IDCAFeeManager.sol
contracts/mocks/DCAFeeManager/DCAFeeManager.sol
test/unit/DCAFeeManager/dca-fee-manager.spec.ts

We are now adding `fillPositions`. This function will allow the contract owner (or allowed users) to take the fees in the contract and deposit it in different positions.

feat: add fill positions

---

contracts/DCAFeeManager/DCAFeeManager.sol
contracts/interfaces/IDCAFeeManager.sol
test/unit/DCAFeeManager/dca-fee-manager.spec.ts

We are now adding a few different methods to be able to withdraw funds from the platform balance, the contract itself or positions

feat: add withdraws

---

contracts/DCAFeeManager/DCAFeeManager.sol
contracts/interfaces/IDCAFeeManager.sol
test/unit/DCAFeeManager/dca-fee-manager.spec.ts

We are now adding a few methods that are meant to be called off-chain. We are adding them so that the contract is easier to use from off-chain clients, that's it

feat: add balance checks

---

contracts/DCAFeeManager/DCAFeeManager.sol
deploy/005_fee_manager.ts
test/integration/DCAFeeManager/dca-fee-manager.spec.ts
test/integration/DCAHubSwapper/swap-for-caller.spec.ts
test/utils/swap-utils.ts

We are now adding Multicall to our contract, and we are also adding an integration test

feat: add multicall and integration test

---

contracts/DCAFeeManager/DCAFeeManager.sol
contracts/interfaces/IDCAFeeManager.sol
contracts/mocks/DCAFeeManager/DCAFeeManager.sol
deploy/005_fee_manager.ts
test/integration/DCAFeeManager/dca-fee-manager.spec.ts
test/integration/DCAHubSwapper/swap-for-caller.spec.ts
test/unit/DCAFeeManager/dca-fee-manager.spec.ts
test/utils/swap-utils.ts

We are now making the tokens distribution configurable. The contract owner (and other allowed users) will be able to set it

feat: add target tokens distribution

---

contracts/DCAFeeManager/DCAFeeManager.sol
contracts/interfaces/IDCAFeeManager.sol
contracts/mocks/DCAFeeManager/DCAFeeManager.sol
deploy/005_fee_manager.ts
test/integration/DCAFeeManager/dca-fee-manager.spec.ts
test/unit/DCAFeeManager/dca-fee-manager.spec.ts

We are now taking the Hub as a parameter when calling`fillPositions`

refactor: take hub address fill positions

---

contracts/DCAHubCompanion/DCAHubCompanionMulticallHandler.sol
contracts/interfaces/IDCAHubCompanion.sol
test/integration/DCAHubCompanion/multi-call.spec.ts
test/unit/DCAHubCompanion/dca-hub-companion-multi-call-handler.spec.ts

We are now taking the `DCAHub` and the `DCAPermissionManager` as parameters on the Companion. Also, we changed the docs so that they were consistent with are new repositories

refactor: add hub as parameter

---

contracts/DCAHubCompanion/DCAHubCompanionHubProxyHandler.sol
contracts/interfaces/IDCAHubCompanion.sol
contracts/mocks/DCAHubCompanion/DCAHubCompanionHubProxyHandler.sol
test/integration/DCAHubCompanion/multi-call.spec.ts
test/unit/DCAHubCompanion/dca-hub-companion-hub-proxy-handler.spec.ts

Some as #104, but with `increasePosition` instead of `deposit`

feat: increase with all balance

---

contracts/DCAHubSwapper/DCAHubSwapper.sol
contracts/DCAHubSwapper/DCAHubSwapperSwapHandler.sol
contracts/mocks/DCAHubSwapper/DCAHubSwapperSwapHandler.sol
deploy/002_swapper.ts
test/integration/V2Migration/position-migrator.spec.ts
test/unit/DCAHubSwapper/dca-hub-swapper-swap-handler.spec.ts

We want to make the DCA Swapper permissiioned, so we are now adding AccessControl + Roles

feat: add roles to dca swapper

---

contracts/DCAFeeManager/DCAFeeManager.sol
contracts/interfaces/IDCAFeeManager.sol
contracts/mocks/DCAFeeManager/DCAFeeManager.sol
test/unit/DCAFeeManager/dca-fee-manager.spec.ts

We are now adding `revokeAllowances` to the FeeManager

feat: add revoke to fee manager

---

test/integration/DCAHubCompanion/position-migrator.spec.ts

We are re-enabling the position migration test, and we also have added the yieldless hub version

test: reenable migration test

---

contracts/DCAHubCompanion/DCAHubCompanionLibrariesHandler.sol
contracts/interfaces/IDCAHubCompanion.sol
contracts/interfaces/IDCAHubSwapper.sol
contracts/interfaces/ILegacyDCAHub.sol
test/integration/DCAHubSwapper/multi-pair-swap-with-dex.spec.ts
test/integration/DCAHubSwapper/single-pair-swap-with-dex.spec.ts
test/integration/DCAHubSwapper/swap-for-caller.spec.ts

We are now adding support for the new params in getNextSwapInfo

refactor: support new params next swap info

---

contracts/DCAStrategies/DCAStrategies/DCAStrategies.sol
contracts/DCAStrategies/DCAStrategies/DCAStrategiesManagementHandler.sol
contracts/DCAStrategies/DCAStrategies/DCAStrategiesPermissionsHandler.sol
contracts/DCAStrategies/DCAStrategies/DCAStrategiesPositionsHandler.sol
contracts/interfaces/IDCAStrategies.sol
package.json
yarn.lock

Create Strategies basic structure:
- create interfaces
- create abstract that inherits from those interfaces
- create main contract that inherits those abstracts
- add nft-descriptor package

feat: basic structure

---

test/integration/DCAHubCompanion/multi-call.spec.ts
test/integration/fork-block-numbers.ts

We are now adding tests that perform swaps. Such as:
- Swap & deposit
- Swap & increase
- Reduce & swap
- Withdraw & swap
- Terminate & swap

test: add swap multi calls

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesPermissionsHandler.sol
contracts/interfaces/IDCAStrategies.sol
contracts/libraries/PermissionMath.sol
contracts/mocks/DCAStrategies/DCAStrategiesPermissionsHandlerMock.sol
test/unit/DCAStrategies/dca-strategies-permissions-handler.spec.ts

- add code for _setPermissions and related vars
- add code for _hasPermission and related vars
- tests everything

feat: set permissions internal

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesPermissionsHandler.sol
test/unit/DCAStrategies/dca-strategies-permissions-handler.spec.ts

- add code for hasPermissions()
- add test for hasPermissions()

feat: has-permissions

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesPermissionsHandler.sol
contracts/interfaces/IDCAStrategies.sol
test/unit/DCAStrategies/dca-strategies-permissions-handler.spec.ts

- add code for modify()
- add code for _modify()
- tests

feat: modify-function

---

contracts/DCAStrategies/DCAStrategies/DCAStrategies.sol
contracts/DCAStrategies/DCAStrategies/DCAStrategiesPermissionsHandler.sol
contracts/interfaces/IDCAStrategies.sol
contracts/mocks/DCAStrategies/DCAStrategiesPermissionsHandlerMock.sol
test/unit/DCAStrategies/dca-strategies-permissions-handler.spec.ts

- add code for permit()
- add related vars
- add tests

feat: permit-function

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesPermissionsHandler.sol
test/unit/DCAStrategies/dca-strategies-permissions-handler.spec.ts

- add code for permissionPermit()
- add code for _encode()
- tests

feat: permission-permit

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesPermissionsHandler.sol
contracts/interfaces/IDCAStrategies.sol
contracts/mocks/DCAStrategies/DCAStrategiesPermissionsHandlerMock.sol
test/unit/DCAStrategies/dca-strategies-permissions-handler.spec.ts

- add code for modifyMany()
- add code for totalSupply()
- add code for DOMAIN_SEPARATOR()
- tests

feat: modify-many-and-some-fn

---

contracts/DCAStrategies/DCAStrategies/DCAStrategies.sol
contracts/DCAStrategies/DCAStrategies/DCAStrategiesPermissionsHandler.sol
contracts/interfaces/IDCAStrategies.sol
contracts/interfaces/IGovernable.sol
contracts/mocks/DCAStrategies/DCAStrategiesPermissionsHandlerMock.sol
contracts/utils/Governable.sol
test/unit/DCAStrategies/dca-strategies-permissions-handler.spec.ts
test/utils/behaviours.ts

- add code for setNftDescriptor()
- add governable.sol
- tests
- also, I changed some code in _behaviours.ts_ file in _utils_, because I used a new governable version

feat: set-nft-descriptor-and-governable

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesPermissionsHandler.sol
test/unit/DCAStrategies/dca-strategies-permissions-handler.spec.ts

- add _beforeTokenTransfer()
- tests

feat: before-token-transfer

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesManagementHandler.sol
contracts/DCAStrategies/DCAStrategies/DCAStrategiesPermissionsHandler.sol
contracts/interfaces/IDCAStrategies.sol
contracts/mocks/DCAStrategies/DCAStrategiesManagementHandlerMock.sol
test/unit/DCAStrategies/dca-strategies-management-handler.spec.ts

I hope is not too much code 😅
- add code for createStrategy()
- add related vars
- new mock
- tests for createStrategy

feat: create-strategy

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesManagementHandler.sol
contracts/interfaces/IDCAStrategies.sol
test/unit/DCAStrategies/dca-strategies-management-handler.spec.ts

- add code for updateStrategyTokens()
- tests

feat: update-strategy-tokens

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesManagementHandler.sol
contracts/interfaces/IDCAStrategies.sol
test/unit/DCAStrategies/dca-strategies-management-handler.spec.ts

- add code for updateStrategyName()
- add code for _checkTokenSharesSanity()
- tests

feat: update-strategy-name-and-others-fn

---

contracts/DCAStrategies/DCAStrategies/DCAStrategies.sol
contracts/DCAStrategies/DCAStrategies/DCAStrategiesManagementHandler.sol
contracts/interfaces/IDCAStrategies.sol
contracts/mocks/DCAStrategies/DCAStrategiesManagementHandlerMock.sol
test/unit/DCAStrategies/dca-strategies-management-handler.spec.ts

- add code for limiting token shares
- tests

feat: token-shares-limit

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesManagementHandler.sol
contracts/interfaces/IDCAStrategies.sol
contracts/mocks/DCAStrategies/DCAStrategiesManagementHandlerMock.sol
test/unit/DCAStrategies/dca-strategies-management-handler.spec.ts

- add code for transferStrategyOwnership()
- tests

feat: transfer-strategy-ownership

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesManagementHandler.sol
contracts/interfaces/IDCAStrategies.sol
test/unit/DCAStrategies/dca-strategies-management-handler.spec.ts

- add code for acceptStrategyOwnership()
- add code for cancelStrategyOwnershipTransfer()
- tests

feat: accept-cancel-strategy-ownership

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesManagementHandler.sol
contracts/DCAStrategies/DCAStrategies/DCAStrategiesPermissionsHandler.sol
contracts/interfaces/IDCAStrategies.sol

I just added some comments in the interface and the abstracts

docs: add-missing-comments

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesManagementHandler.sol
contracts/DCAStrategies/DCAStrategies/DCAStrategiesPermissionsHandler.sol

I re-orderer some vars and functions

fix: re-order-vars-and-functions

---

contracts/DCAStrategies/DCAStrategies/DCAStrategies.sol
contracts/DCAStrategies/DCAStrategies/DCAStrategiesManagementHandler.sol
contracts/DCAStrategies/DCAStrategies/DCAStrategiesPositionsHandler.sol
contracts/interfaces/IDCAStrategies.sol
contracts/mocks/DCAStrategies/DCAStrategiesPositionsHandlerMock.sol
test/unit/DCAStrategies/dca-strategies-positions-handler.spec.ts

- re-order contracts and inheritance
- add code for deposit()
- tests

feat: deposit

---

contracts/DCAStrategies/DCAStrategies/DCAStrategies.sol
contracts/DCAStrategies/DCAStrategies/DCAStrategiesPositionsHandler.sol
contracts/mocks/DCAStrategies/DCAStrategiesPositionsHandlerMock.sol
test/unit/DCAStrategies/dca-strategies-positions-handler.spec.ts

- add code for internal loop in deposit()
- tests

feat: deposit-internal-loop

---

contracts/DCAStrategies/DCAStrategies/DCAStrategies.sol
contracts/DCAStrategies/DCAStrategies/DCAStrategiesPermissionsHandler.sol
contracts/DCAStrategies/DCAStrategies/DCAStrategiesPositionsHandler.sol
contracts/interfaces/IDCAStrategies.sol
contracts/mocks/DCAStrategies/DCAStrategiesPositionsHandlerMock.sol
test/unit/DCAStrategies/dca-strategies-positions-handler.spec.ts

- add code for withdrawSwapped()
- tests

feat: withdraw-swapped

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesPositionsHandler.sol
contracts/interfaces/IDCAStrategies.sol
test/unit/DCAStrategies/dca-strategies-positions-handler.spec.ts

- add code for increasePosition()
- improvements
- tests

feat: increase-position

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesPositionsHandler.sol
contracts/interfaces/IDCAStrategies.sol
test/unit/DCAStrategies/dca-strategies-positions-handler.spec.ts

- add code for reducePosition()
- tests

feat: reduce-position

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesPositionsHandler.sol
contracts/interfaces/IDCAStrategies.sol
test/unit/DCAStrategies/dca-strategies-positions-handler.spec.ts

- add code for terminate()
- tests

feat: terminate-position

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesManagementHandler.sol
contracts/DCAStrategies/DCAStrategies/DCAStrategiesPositionsHandler.sol
contracts/interfaces/IDCAStrategies.sol
test/unit/DCAStrategies/dca-strategies-management-handler.spec.ts

- create function ` _checkTokenSharesSanity()`
- tests
- prepare code for next PR

feat: preparation-for-sync-to-latest

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesPositionsHandler.sol
contracts/interfaces/IDCAStrategies.sol

- add code for sync function. I coded the first while of the entire function (from the start to line 70 in the prototype)
- also, I will left gas optimization and tests for the end

feat: sync-to-latest

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesPositionsHandler.sol
contracts/interfaces/IDCAStrategies.sol

- finish sync function
- tests will be on the next PR

feat: sync-to-latest-2

---

contracts/DCAFeeManager/DCAFeeManager.sol
contracts/DCAHubCompanion/DCAHubCompanionHubProxyHandler.sol

We are now using unchecked in for loops, and we avoiding unnecessary array reads to make some small gas savings

perf: some minor optimizations

---

contracts/DCAStrategies/DCAStrategies/DCAStrategiesPositionsHandler.sol
contracts/mocks/DCAStrategies/DCAStrategiesPositionsHandlerMock.sol
test/unit/DCAStrategies/dca-strategies-management-handler.spec.ts
test/unit/DCAStrategies/dca-strategies-positions-handler.spec.ts

- add tests for sync function
- fix errors

feat: sync-to-latest-tests

---

contracts/DCAStrategies/DCAStrategies/DCAStrategies.sol
contracts/interfaces/IDCAStrategies.sol
test/unit/DCAStrategies/dca-strategies-management-handler.spec.ts
test/unit/DCAStrategies/dca-strategies-positions-handler.spec.ts

add natspec comments, fix tests

feat: strategies-miscellaneous

---

contracts/DCAKeep3rJob/DCAKeep3rJob.sol
contracts/interfaces/IDCAKeep3rJob.sol
test/unit/DCAKeep3rJob/dca-keep3r-job.spec.ts

We are now adding `setSwapper` to the keep3r job

feat: add set swapper to keep3r job

---

contracts/DCAKeep3rJob/DCAKeep3rJob.sol
contracts/interfaces/IDCAKeep3rJob.sol
test/unit/DCAKeep3rJob/dca-keep3r-job.spec.ts

We are now implementing the job's `work` function

feat: add keep3r job work

---

deploy/004_keep3r_job.ts
test/integration/DCAHubSwapper/multi-pair-swap-with-dex.spec.ts
test/integration/DCAHubSwapper/optimized-multi-pair-swap-with-dex.spec.ts
test/integration/DCAHubSwapper/single-pair-swap-with-dex.spec.ts
test/integration/DCAKeep3rJob/keep3r-job.spec.ts
test/integration/abis/Keep3r.json
test/integration/utils.ts

We are now adding an integration test for the keep3r job

test: add keep3r integration test

---

contracts/DCAHubSwapper/ThirdPartyDCAHubSwapper.sol
test/unit/DCAHubSwapper/third-party-dca-hub-swapper.spec.ts

We realized that we were not making any permissions check on the new `executeSwap` call, which would allow anyone to execute swaps
So instead of building a new control module, we simply ask the hub if the caller has privileged swap permissions

fix: check if privileged swapper

---

.github/workflows/tests.yml

Apparently we are making too many requests for alchemy, so we are trying alternatives

chore: change rpc for tests

---

contracts/utils/BaseCompanion.sol
package.json
yarn.lock

We are now adding the new Simulation Adapter to the companion, so that we can simulate multiple quotes before executing them

feat: add simulation adapter

---

contracts/DCAFeeManager/DCAFeeManager.sol
contracts/interfaces/IDCAFeeManager.sol

We are now adding simulation capabilities with the fee manager

feat: add simulation adapter to fee manager
